### ISSUE TITLE
How use a store in interactive queries when it has been made by a Process API

### ISSUE THREAD

**Issue by dahuchao** [confluentinc/kafka-streams-examples#126]
In that post : 
https://stackoverflow.com/a/50752095/9234107

_you might be able to use a "global store" instead of a GlobalKTable. For this case, you can provide a custom Processor that can implement a filter before you populate the global store._

So I initialize my spring bean like this : 

```java
@PostConstruct
private void init() {
	configurer();
	producer = new KafkaProducer<>(props);
	journal.info("Open topic {}...", kafkaTopic);
	StreamsBuilder builder = new StreamsBuilder();
	Topology topology = builder.build();
	StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
			Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
			Serdes.serdeFrom(CustomerAvro.class));
	topology.addSource("person$", kafkaTopic)
			.addProcessor("selection", PersonProcessor::new, "person$")
			.addStateStore(personStoreSupplier, "selection");
	store = personStoreSupplier.build();
	KafkaStreams streams = new KafkaStreams(topology, props);
	streams.start();
}
```

And my processor is like this

```java

public class PersonProcessor extends AbstractProcessor<String, PersonAvro> {
	private KeyValueStore<String, CustomerAvro> stateStore;

	@Override
	public void process(String key, PersonAvro avroPerson) {
		Optional.ofNullable(avroPerson)
				.filter(person -> Optional.ofNullable(person)
						.map(PersonAvro::getActive)
						.map(activation -> !activation.matches("0"))
					.isPresent())
			.map(person -> {
				return CustomerAvro.newBuilder()
						.setId(person.getId())
						.setCompName(person.getCompName())
						.setSiretCode(person.getSiretCode())
						.setActive(person.getActive())
						.setAdd3(person.getAdd3())
						.setAdd4(person.getAdd4())
						.setAdd5(person.getAdd5())
						.setAdd6(person.getAdd6())
						.setAdd7(person.getAdd7());
			})
			.map(CustomerAvro.Builder::build)
			.ifPresent(person -> {
				stateStore.put(key, person);
				context().forward(key, person);
				context().commit();
			});
}

@Override
public void init(ProcessorContext context) {
	super.init(context);
	stateStore = (KeyValueStore<String, CustomerAvro>) context.getStateStore("personStore");
}
```

But how can I use the store in interactive queries ? For exemple to get the state of one customer.

And after i will make a global state but step by step :-)

Thank's

**Comment by mjsax** [comment]
Side remark: Why do you call `store = personStoreSupplier.build();`?

Interactive Queries are described here: https://docs.confluent.io/current/streams/developer-guide/interactive-queries.html#querying-local-key-value-stores

**Comment by dahuchao** [comment]
Yes ! In the documentation i see the "get" method on a store. I need that method to respond to HTTP GET requests : 

```java
@Service
@ConfigurationProperties(prefix = "person")
public class PersonService8 extends BsccServiceKafka<String, Long> implements PersonService {
	Logger journal = LoggerFactory.getLogger(PersonService8.class);
	Producer<String, PersonAvro> producer;
	ReadOnlyKeyValueStore<String, CustomerAvro> store;

	@Value("${customer.kafka-topic}")
	String customerTopic;

	@PostConstruct
	private void init() {
		configurer();
		producer = new KafkaProducer<>(props);
		journal.info("Open topic {}...", kafkaTopic);
		StreamsBuilder builder = new StreamsBuilder();
		Topology topology = builder.build();

		Serde<CustomerAvro> serdeCustomer = new SpecificAvroSerde<>();

		StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
				Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
				Serdes.serdeFrom(serdeCustomer.serializer(), serdeCustomer.deserializer()));
		topology.addSource("person$", kafkaTopic)
				.addProcessor("selection", PersonProcessor2::new, "person$")
				.addStateStore(personStoreSupplier, "selection");
		store = personStoreSupplier.build();
		KafkaStreams streams = new KafkaStreams(topology, props);
		streams.start();
	}

	public Mono<CustomerAvro> get(int id) {
		journal.debug("Recherche customer by id: {}", id);
		return Mono.just(id)
				.map(String::valueOf)
				.map(store::get)
				.onErrorResume(e -> Mono.empty());
	}
...
```

So i build the "store" attribut of the PersonService8 service in his PersonService8::init method in order to have it in the PersonService8::get method.

But there is something wrong because when i execute that code, i got that error : 

`org.apache.kafka.streams.errors.InvalidStateStoreException: Store personProcessStore is currently closed`

Thank's a lot for help.

**Comment by dahuchao** [comment]
Instead of building the store, i tried to find it by this way

```java
	@PostConstruct
	private void init() throws InterruptedException {
		configurer();
		producer = new KafkaProducer<>(props);
		journal.info("Open topic {}...", kafkaTopic);
		StreamsBuilder builder = new StreamsBuilder();
		Topology topology = builder.build();
		Serde<CustomerAvro> serdeCustomer = new SpecificAvroSerde<>();
		StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
				Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
				Serdes.serdeFrom(serdeCustomer.serializer(), serdeCustomer.deserializer()));
		topology.addSource("person$", kafkaTopic)
				.addProcessor("selection", PersonProcessor2::new, "person$")
				.addStateStore(personStoreSupplier, "selection");
//		store = personStoreSupplier.build();
		KafkaStreams streams = new KafkaStreams(topology, props);
		streams.start();
		store = waitUntilStoreIsQueryable("personProcessStore", streams);
	}
```

```java
	public ReadOnlyKeyValueStore<K, V> waitUntilStoreIsQueryable(final String storeName, final KafkaStreams streams)
			throws InterruptedException {
		journal.info("Attente store ...");
		while (true) {
			try {
				return streams.store(storeName, QueryableStoreTypes.<K, V>keyValueStore());
			} catch (InvalidStateStoreException ignored) {
				// Journalisation
				journal.info(String.format("topic(%s) appid(%s): %s", kafkaTopic, kafkaAppid, ignored.getMessage()));
				// store not yet ready for querying
				Thread.sleep(500);
			}
		}
	}
```

But KeyValueStore::put method invocation throws that error : 
```
14:19:25.063 DEBUG f.l.b.e.c.person.PersonProcessor2 - traitement objet: 0, 2
14:19:25.063 DEBUG f.l.b.e.c.person.PersonProcessor2 - enregistrement message: key:0, value:{"id": "0", "compName": "island", "add3": "1183 Walnut Court", "add4": "1797 Schwallie Crescent", "add5": "911 Eller Ridge", "add6": "1311 Langan Square", "add7": "1430 Lithopolis Ridge", "countryCode": "handled", "active": "2", "siretCode": "should"}
14:19:26.432 INFO  f.l.b.e.EncaissementApplication - Started EncaissementApplication in 6.084 seconds (JVM running for 7.275)
14:20:06.191 ERROR o.a.k.s.p.internals.AssignedTasks - stream-thread [pr_loc_u0_person-740dd4e3-b3e1-41be-9aeb-8d9386331280-StreamThread-1] Failed to process stream task 0_0 due to the following error:
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=person$, topic=pr_loc_person_priv_v1, partition=0, offset=0
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:235)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.process(AssignedTasks.java:404)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:318)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:942)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:822)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:774)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:744)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException: null
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:82)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
	at io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer.serialize(SpecificAvroSerializer.java:65)
	at io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer.serialize(SpecificAvroSerializer.java:38)
	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:178)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore$1.innerValue(MeteredKeyValueBytesStore.java:68)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore$1.innerValue(MeteredKeyValueBytesStore.java:57)
	at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.put(InnerMeteredKeyValueStore.java:199)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.put(MeteredKeyValueBytesStore.java:121)
	at fr.laposte.bscc.encaissement.coclico.person.PersonProcessor2.lambda$5(PersonProcessor2.java:44)
	at java.util.Optional.ifPresent(Optional.java:159)
	at fr.laposte.bscc.encaissement.coclico.person.PersonProcessor2.process(PersonProcessor2.java:42)
	at fr.laposte.bscc.encaissement.coclico.person.PersonProcessor2.process(PersonProcessor2.java:1)
```

I don't understand what's wrong :-(

**Comment by mjsax** [comment]
The Avro Serde need to be configured. Because, you create the Serde object in your code (`Serde<CustomerAvro> serdeCustomer = new SpecificAvroSerde<>();`), what is absolutely fine, you also need to configure the Serde in your code and call `serdeCustomer.configure()` to pass in schema registry information.

**Comment by jdang67** [comment]
I'm using the same technique to create anew StateStore<Strinng, CustomObject> where CustomObject is Avro and still see exception: Error deserializing Avro message for id -1.
Any working example to share?

**Comment by mjsax** [comment]
Can you share a code snippet how you create the store and serdes?
