### ISSUE TITLE
Microservices example: Add jersey-hk2 dependency to pom

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-streams-examples#129]
In 5.0.x:

Trying to piece out the microservices example and run OrdersService standalone (outside of `io.confluent.examples.streams.microservices.EndToEndTest`):

```bash
$ mvn exec:java -Dexec.mainClass=io.confluent.examples.streams.microservices.OrdersService
```

However it fails:

```bash
Caused by: java.lang.RuntimeException: javax.servlet.ServletException: org.glassfish.jersey.servlet.ServletContainer-f71f946@e6d289c7==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=false
    at io.confluent.examples.streams.microservices.util.MicroserviceUtils.startJetty(MicroserviceUtils.java:154)
    at io.confluent.examples.streams.microservices.OrdersService.start(OrdersService.java:314)
    at io.confluent.examples.streams.microservices.OrdersService.main(OrdersService.java:396)
    ... 6 more
Caused by: javax.servlet.ServletException: org.glassfish.jersey.servlet.ServletContainer-f71f946@e6d289c7==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=false
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:691)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
    at org.eclipse.jetty.server.Server.start(Server.java:419)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
    at org.eclipse.jetty.server.Server.doStart(Server.java:386)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at io.confluent.examples.streams.microservices.util.MicroserviceUtils.startJetty(MicroserviceUtils.java:152)
    ... 8 more
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
    at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
    at java.util.Optional.orElseThrow(Optional.java:290)
    at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
    at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93)
    at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
    at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
    ... 21 more
```

Adding the following dependency to the pom file seems to work:

```bash
    <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>${jersey.version}</version>
     </dependency>
```

**Comment by ybyzek** [comment]
Closing this issue because it has been resolved in #134
