### ISSUE TITLE
Deleting topics throws exception

### ISSUE THREAD

**Issue by handstand2002** [confluentinc/kafka-streams-examples#196]
When running EmbeddedSingleNodeKafkaCluster#deleteTopicsAndWait, Exception occurs if topics exist, and topics aren't deleted. Have confirmed this on 2 machines (Windows 8.1 and Windows 10, both using java version 1.8.0_181).

Exception:
```
Caused by: java.nio.file.AccessDeniedException: C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0 -> C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0.a3c80cfca5e740bd8c1be434d817af2c-delete
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:809)
        at kafka.log.Log$$anonfun$renameDir$1.apply$mcV$sp(Log.scala:728)
        at kafka.log.Log$$anonfun$renameDir$1.apply(Log.scala:726)
        at kafka.log.Log$$anonfun$renameDir$1.apply(Log.scala:726)
        at kafka.log.Log.maybeHandleIOException(Log.scala:1927)
        at kafka.log.Log.renameDir(Log.scala:726)
        at kafka.log.LogManager.asyncDelete(LogManager.scala:842)
        at kafka.cluster.Partition$$anonfun$delete$1.apply(Partition.scala:353)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:259)
        at kafka.cluster.Partition.delete(Partition.scala:347)
        at kafka.server.ReplicaManager.stopReplica(ReplicaManager.scala:350)
        at kafka.server.ReplicaManager$$anonfun$stopReplicas$2.apply(ReplicaManager.scala:380)
        at kafka.server.ReplicaManager$$anonfun$stopReplicas$2.apply(ReplicaManager.scala:378)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.server.ReplicaManager.stopReplicas(ReplicaManager.scala:378)
        at kafka.server.KafkaApis.handleStopReplicaRequest(KafkaApis.scala:200)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:111)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:69)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.nio.file.AccessDeniedException: C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0 -> C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0.a3c80cfca5e740bd8c1be434d817af2c-delete
                at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
                at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
                at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
                at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
                at java.nio.file.Files.move(Files.java:1395)
                at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:806)
                ... 22 more
```

This is recreated by this test
https://pastebin.com/Rt0uZjDk

**Comment by mjsax** [comment]
Not sure what this is raised against our examples repo. Can you elaborate?

**Comment by handstand2002** [comment]
in the class EmbeddedSingleNodeKafkaCluster used in the example tests, the method deleteTopicsAndWait produces Exceptions (and doesn't delete topics) if any topics have been created.

As far as I can tell, the problem code is in this repo, so that's why I've raised the issue here. If you believe I should raise an issue elsewhere, I'd be happy to.

**Comment by mjsax** [comment]
Can you specify which test is affected? It's not clear from the provided stack trace.

**Comment by handstand2002** [comment]
Sorry, must feel like pulling teeth getting this info from me - I'm not all here today.

Running tests in the class "OrdersServiceTest" throws the above exception as soon as it runs ```prepareKafkaCluster()``` the 2nd time. The first time there wasn't an error since there weren't any topics in cluster yet.

**Comment by mjsax** [comment]
Thanks. I am not 100% sure, we usually don't test on Windows OS. Kafka's target platform is Linux.

It seems that a file cannot be renamed:
```
        Suppressed: java.nio.file.AccessDeniedException: C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0 -> C:\Users\gwade\AppData\Local\Temp\junit6747789160683566966\junit5490786451417386230\topic-0.a3c80cfca5e740bd8c1be434d817af2c-delete
```

`topic-0` would be partition zero of topic "topic" (that's a directory). The broker tries to rename it when it deletes it, and this renaming seems to fail.

I would recommend to use a non-Windows platform.

**Comment by leopardy** [comment]
Since it's not cool to continue offering a Windows distribution and later cop out by saying, don't use the Windows distribution, the following is what worked for me when deleting a topic:

C:\kafka_2.13-2.4.0>.\bin\windows\kafka-topics.bat --zookeeper localhost:2181 --delete --topic mytopic

Since this only marks it for deletion, I then 
rebooted machine, restarted zookeeper and kafka, and re-ran the app that I had originally used to create the topic(don't remember what order I did the steps in).

This worked for me one time but not others.
In that case I had to go to C:\tmp and remove both zookeeper and kafka-logs

**Comment by zeinabkamel** [comment]
also i have  problem when     i try  to delete  Kafka  topic  
Kafka   crash   and  stopped 
![Select Command Prompt 3_5_2020 4_15_10 PM](https://user-images.githubusercontent.com/47484937/75990120-1331f780-5efd-11ea-9410-b7b3727845cd.png)

**Comment by mjsax** [comment]
> Since it's not cool to continue offering a Windows distribution and later cop out by saying, don't use the Windows distribution

Not sure what you mean by "Windows distribution". We clearly state what OS are supported: https://docs.confluent.io/current/installation/system-requirements.html#operating-systems

**Comment by raedbenz** [comment]
this issue hasnt gone wondering why is closed.

**Comment by mjsax** [comment]
The ticket is closed because Confluent does not officially support Windows OS. Also, this is an examples repository and there is no issue with the examples themselves and that could be fixed in this repo.

Feel free to create a ticket against the Apache Kafka project to report he issue there: https://issues.apache.org/jira/browse/

**Comment by javaHelper** [comment]
I am frustrated to see below error in kafka_2.13-3.0.0, any quick work around?

```sh
[2021-11-18 21:33:18,908] INFO Stat of the created znode at /brokers/ids/0 is: 42,42,1637251397733,1637251397733,1,0,0,72086256842768385,202,0,42
 (kafka.zk.KafkaZkClient)
[2021-11-18 21:33:18,913] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://localhost:9092, czxid (broker epoch): 42 (kafka.zk.KafkaZkClient)
[2021-11-18 21:33:19,074] ERROR Failed to write meta.properties due to (kafka.server.BrokerMetadataCheckpoint)
java.nio.file.AccessDeniedException: C:\data\kafka-logs
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
        at org.apache.kafka.common.utils.Utils.flushDir(Utils.java:953)
        at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:941)
        at kafka.server.BrokerMetadataCheckpoint.liftedTree1$1(BrokerMetadataCheckpoint.scala:214)
        at kafka.server.BrokerMetadataCheckpoint.write(BrokerMetadataCheckpoint.scala:204)
        at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2(KafkaServer.scala:772)
        at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2$adapted(KafkaServer.scala:770)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
        at kafka.server.KafkaServer.checkpointBrokerMetadata(KafkaServer.scala:770)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:322)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
[2021-11-18 21:33:19,094] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.nio.file.AccessDeniedException: C:\data\kafka-logs
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
        at org.apache.kafka.common.utils.Utils.flushDir(Utils.java:953)
        at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:941)
        at kafka.server.BrokerMetadataCheckpoint.liftedTree1$1(BrokerMetadataCheckpoint.scala:214)
        at kafka.server.BrokerMetadataCheckpoint.write(BrokerMetadataCheckpoint.scala:204)
        at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2(KafkaServer.scala:772)
        at kafka.server.KafkaServer.$anonfun$checkpointBrokerMetadata$2$adapted(KafkaServer.scala:770)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
        at kafka.server.KafkaServer.checkpointBrokerMetadata(KafkaServer.scala:770)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:322)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
```

**Comment by Sam-Dragon** [comment]
Step 1: Terminate all command prompts which runs zookeeper, kafka server and close all of them 
Step 2: Go to the folder where both zookeeper folder & kafka-logs are present and delete it 
[You can find the path in server.properties and zookeeper.properties]
Step 3: Now try running again, it must work

**Comment by credmond** [comment]
> Step 1: Terminate all command prompts which runs zookeeper, kafka server and close all of them Step 2: Go to the folder where both zookeeper folder & kafka-logs are present and delete it [You can find the path in server.properties and zookeeper.properties] Step 3: Now try running again, it must work

That's no good from a test perspective, which is what this ticket is about.
