### ISSUE TITLE
Could not find class io.confluent.connect.avro.ConnectDefault

### ISSUE THREAD

**Issue by jessicashin** [confluentinc/kafka-streams-examples#22]
I am using a jdbc source connector with query mode. It seems that without a specified table name, the schemas registered in the schema-registry for the record key and record value have empty schema names and are being assigned the default name "ConnectDefault" as defined in Confluent's AvroData class https://github.com/confluentinc/schema-registry/blob/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java

When running a Kafka Streams application using generated avro sources and SpecificAvroSerde, I am getting the error:
```
Exception in thread "streams-app-6e39ebfd-db14-49bc-834f-afaf108a6d25-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Failed to deserialize value for record. topic=topic-name, partition=0, offset=0
  at org.apache.kafka.streams.processor.internals.SourceNodeRecordDeserializer.deserialize(SourceNodeRecordDeserializer.java:46)
  at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:84)
  at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
  at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:474)
  at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:642)
  at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:548)
  at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:519)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 2
Caused by: org.apache.kafka.common.errors.SerializationException: Could not find class io.confluent.connect.avro.ConnectDefault specified in writer's schema whilst finding reader's schema for a SpecificRecord.
```

When running a sink connector reading from the topic there are no issues. The exception is only caused in the streams layer with the deserialization.

I have tried to POST a new version of both the key and value schemas from the topic with a table name as the schema name and DELETE the original versions that had the `\"name\":\"ConnectDefault\",\"namespace\":\"io.confluent.connect.avro\"` properties with no luck. Am I missing a class named ConnectDefault or can I specify somewhere in the source connector a schema name without the namespace?

**Comment by JanardhanVarikuti** [comment]
Hi @jessicashin , Is the above issue is resolved? If yes, could you please provide the solution?

**Comment by jessicashin** [comment]
@JanardhanVarikuti I was able to get the streams app working initially when reading from a single topic by just changing the avro schema file to have those default values: `"name": "ConnectDefault"` with `"namespace": "io.confluent.connect.avro"`. So my generated class was just called ConnectDefault.java

In order to have multiple streams in the same application, you can use the Kafka SMT (Single Message Transforms) SetSchemaMetadata in each source connector config to set the schema names.
```
transforms=SetSchemaName
transforms.SetSchemaName.type=org.apache.kafka.connect.transforms.SetSchemaMetadata$Value
transforms.SetSchemaName.schema.name=MyClassName
```
This way you can use `"name": "MyClassName"` in the avro schema file. But since you cannot specify the namespace with SMT, you will need to put your streams app in the default package and omit the namespace in the avro schema files for your generated sources.

**Comment by dekelmos** [comment]
You can add your package under name. e.g:
transforms.SetSchemaName.schema.name=com.mysolution.MyClassName

**Comment by fjbsantiago** [comment]
Guys, thank you. I love it when I found someone struggling for exactly the same thing.

I used your combined advices @dekelmos and @jessicashin:

```
transforms=SetSchemaName
transforms.SetSchemaName.type=org.apache.kafka.connect.transforms.SetSchemaMetadata$Value
transforms.SetSchemaName.schema.name=com.mysolution.MyClassName
```

Thank you.
