### ISSUE TITLE
Starting OrderServiceTest in IntelliJ causes AccessDeniedException for 3 of the 4 Tests

### ISSUE THREAD

**Issue by keltik85** [confluentinc/kafka-streams-examples#321]
Hi,

When I execute the OrderServiceTest I get this exception:

```
Caused by: java.nio.file.AccessDeniedException: C:\Users\my-windows-10-user\AppData\Local\Temp\junit4909748072229509906\junit787894280065180465\orders-0 -> C:\Users\my-windows-10-user\AppData\Local\Temp\junit4909748072229509906\junit787894280065180465\orders-0.527e5b93c9a04ca18ba9547d9fe29342-delete
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:795)
	at kafka.log.Log.$anonfun$renameDir$2(Log.scala:966)
	at kafka.log.Log.renameDir(Log.scala:2316)
	at kafka.log.LogManager.asyncDelete(LogManager.scala:925)
	at kafka.cluster.Partition.$anonfun$delete$1(Partition.scala:479)
	at kafka.cluster.Partition.delete(Partition.scala:470)
	at kafka.server.ReplicaManager.stopReplica(ReplicaManager.scala:360)
	at kafka.server.ReplicaManager.$anonfun$stopReplicas$2(ReplicaManager.scala:404)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at kafka.server.ReplicaManager.stopReplicas(ReplicaManager.scala:402)
	at kafka.server.KafkaApis.handleStopReplicaRequest(KafkaApis.scala:235)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:131)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.file.AccessDeniedException: C:\Users\my-windows-10-user\AppData\Local\Temp\junit4909748072229509906\junit787894280065180465\orders-0 -> C:\Users\my-windows-10-user\AppData\Local\Temp\junit4909748072229509906\junit787894280065180465\orders-0.527e5b93c9a04ca18ba9547d9fe29342-delete
		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:792)
		... 13 more
```

Here is a Screenshot:

![kafka-test-error](https://user-images.githubusercontent.com/13469004/75467959-bda19c00-598c-11ea-8d37-84a2b50497f6.PNG)

Please tell me what additional info you need.

**Comment by mjsax** [comment]
There are known issues on Windows OS. I would recommend to run on Linux.

**Comment by mjsax** [comment]
Closing due to inactivity.
