### ISSUE TITLE
Failed to create dir: Invalid argument at Windows

### ISSUE THREAD

**Issue by nikolayspb** [confluentinc/kafka-streams-examples#52]
I ran example file EventDeduplicationLambdaIntegrationTest and get following exception at Windows 10.

```
[2018-01-16 00:38:46,485] WARN [main] [Consumer clientId=consumer-1, groupId=deduplication-integration-test-standard-consumer] Synchronous auto-commit of offsets {outputTopic-0=OffsetAndMetadata{offset=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
Exception in thread "deduplication-lambda-integration-test-219b1b1a-3754-47b1-abe3-7ecdc75dc0f2-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=inputTopic, partition=0, offset=0
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:232)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.process(AssignedTasks.java:403)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:317)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:942)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:822)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:774)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:744)
Caused by: org.apache.kafka.streams.errors.ProcessorStateException: Error opening store eventId-store:1516052100000 at location C:\Users\NKUZNE~1\AppData\Local\Temp\kafka-3711583845759769165\deduplication-lambda-integration-test\0_0\eventId-store\eventId-store:1516052100000
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:204)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:174)
	at org.apache.kafka.streams.state.internals.Segment.openDB(Segment.java:40)
	at org.apache.kafka.streams.state.internals.Segments.getOrCreateSegment(Segments.java:89)
	at org.apache.kafka.streams.state.internals.RocksDBSegmentedBytesStore.put(RocksDBSegmentedBytesStore.java:81)
	at org.apache.kafka.streams.state.internals.RocksDBWindowStore$RocksDBWindowBytesStore.put(RocksDBWindowStore.java:43)
	at org.apache.kafka.streams.state.internals.RocksDBWindowStore$RocksDBWindowBytesStore.put(RocksDBWindowStore.java:34)
	at org.apache.kafka.streams.state.internals.ChangeLoggingWindowBytesStore.put(ChangeLoggingWindowBytesStore.java:67)
	at org.apache.kafka.streams.state.internals.ChangeLoggingWindowBytesStore.put(ChangeLoggingWindowBytesStore.java:33)
	at org.apache.kafka.streams.state.internals.MeteredWindowStore.put(MeteredWindowStore.java:96)
	at io.confluent.examples.streams.EventDeduplicationLambdaIntegrationTest$DeduplicationTransformer.rememberNewEvent(EventDeduplicationLambdaIntegrationTest.java:174)
	at io.confluent.examples.streams.EventDeduplicationLambdaIntegrationTest$DeduplicationTransformer.transform(EventDeduplicationLambdaIntegrationTest.java:152)
	at io.confluent.examples.streams.EventDeduplicationLambdaIntegrationTest$DeduplicationTransformer.transform(EventDeduplicationLambdaIntegrationTest.java:100)
	at org.apache.kafka.streams.kstream.internals.KStreamTransform$KStreamTransformProcessor.process(KStreamTransform.java:56)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:216)
	... 6 more
Caused by: org.rocksdb.RocksDBException: Failed to create dir: C:\Users\NKUZNE~1\AppData\Local\Temp\kafka-3711583845759769165\deduplication-lambda-integration-test\0_0\eventId-store\eventId-store:1516052100000: Invalid argument
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:231)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:197)
	... 25 more
```

**Comment by mjsax** [comment]
This is a know bug in Kafka Streams `1.0.0`. It's already fixed in `trunk`. Thus, the fix will be contained in `1.0.1` and `1.1.0`.

https://issues.apache.org/jira/browse/KAFKA-6167
