### ISSUE TITLE
Exception in thread "kafka-music-charts-53af5ee5-082b-419b-93fd-5efbc5c23e29-StreamThread-1" java.lang.ExceptionInInitializerError at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64).

### ISSUE THREAD

**Issue by bhagyashri10** [confluentinc/kafka-streams-examples#91]
I am using eclipse to run KafkaMusicExample,the below RuntimeException occured while running:

```
Exception in thread "kafka-music-charts-53af5ee5-082b-419b-93fd-5efbc5c23e29-StreamThread-1" java.lang.ExceptionInInitializerError
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.Options.<clinit>(Options.java:25)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:128)
	at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:185)
	at org.apache.kafka.streams.state.internals.ChangeLoggingKeyValueBytesStore.init(ChangeLoggingKeyValueBytesStore.java:40)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:59)
	at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.init(InnerMeteredKeyValueStore.java:160)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.init(MeteredKeyValueBytesStore.java:104)
	at org.apache.kafka.streams.processor.internals.AbstractTask.registerStateStores(AbstractTask.java:225)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeStateStores(StreamTask.java:163)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.initializeNewTasks(AssignedTasks.java:122)
	at org.apache.kafka.streams.processor.internals.TaskManager.updateNewAndRestoringTasks(TaskManager.java:260)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:813)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:774)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:744)
Caused by: java.lang.UnsupportedOperationException: Cannot determine JNI library name for ARCH='x86' OS='windows 10' name='rocksdb'
	at org.rocksdb.util.Environment.getJniLibraryName(Environment.java:66)
	at org.rocksdb.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:19)
	... 16 more
```

I am using 5.9.2 version of rocksdbjni on windows 10,  64-bit machine.

**Comment by bhagyashri10** [comment]
Problem solved by changing jre 32-bit to 64-bit.
